# Examination link has to be an xlsx file
exams: link-of-exams.xlsx
# For docker container it should be 0.0.0.0
hostname: hostname-of-the-api
port: port-of-the-api
redis:
  Ann_DB: 0
  Users_DB: 1
  Tokens_DB: 2
