matrix:
  include:
    - os: linux
      services: docker
      install:
        - curl -sL https://sentry.io/get-cli/ | bash
      script:
        - docker-compose build --parallel
      deploy:
        provider: script
        script: bash deploy
        on:
          tags: true
cache:
  directories:
    - node_modules
