matrix:
  include:
    - os: linux
      services: docker
      script:
        - docker-compose build --parallel
      deploy:
        provider: script
        script: bash docker_push
        on:
          tags: true
cache:
  directories:
    - node_modules
