matrix:
  include:
  - os: linux
    language: node_js
    node_js: '12'
    script:
    - make .build-web
  - os: linux
    services: docker
    language: go
    go: '1.14'
    script:
      - docker-compose build
    deploy:
      provider: script
      script: bash docker_push
      on:
        branch: master
cache:
  directories:
  - node_modules
