matrix:
  include:
    - os: linux
      language: node_js
      node_js: '12'
      script:
        - docker-compose build frontend
    - os: linux
      services: docker
      language: go
      go: '1.14'
      script:
        - docker-compose build backend
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
cache:
  directories:
    - node_modules
