matrix:
  include:
  - os: linux
    language: node_js
    node_js: '12'
    script:
    - make .build-web
  - os: linux
    language: go
    go: '1.14'
    script:
    - make .build-go
    env:
    - GO111MODULE=on
cache:
  directories:
  - node_modules