matrix:
  include:
    - os: linux
      services: docker
      script:
        - docker-compose build
      deploy:
        provider: script
        script: bash docker_push
        on:
          branch: master
cache:
  directories:
    - node_modules