language: go
go: '1.14'

matrix:
  include:
    - stage: "Test"
      env:
        - POSTGRES_URI="postgresql://postgresuser:pass@postgres:24000/postgres?sslmode=disable"
        - REDIS_URI="redis:24001"
        - REDIS_PASSWORD="secret"
      script:
        - docker-compose -f docker-compose.test.yml up -d
        - make test
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: "Build images"
      install:
        - curl -sL https://sentry.io/get-cli/ | bash
      script:
        - LATEST_TAG=$(git rev-parse $(git describe --abbrev=0 --tags))
        - SHA=$(git rev-parse $LATEST_TAG)
        - sed -i "s/@.*\"/@"$SHA"\"/" $TRAVIS_BUILD_DIR/backend/main.go
        - sed -i "s/sha'/@"$SHA"'/" $TRAVIS_BUILD_DIR/app/src/main.js
        - docker-compose build --parallel
      deploy:
        provider: script
        script: bash deploy
        on:
          tags: true
cache:
  directories:
    - node_modules
