matrix:
  include:
    - os: linux
      services: docker
      install:
        - curl -sL https://sentry.io/get-cli/ | bash
      script:
        - LATEST_TAG=$(git rev-parse $(git describe --abbrev=0 --tags))
        - SHA=$(git rev-parse $LATEST_TAG)
        - sed -i "s/@.*\"/@"$SHA"\"/" $TRAVIS_BUILD_DIR/backend/main.go
        - sed -i "s/@.*'/@"$SHA"'/" $TRAVIS_BUILD_DIR/app/src/main.js
        - docker-compose build --parallel
      deploy:
        provider: script
        script: bash deploy
        on:
          tags: true
cache:
  directories:
    - node_modules
