matrix:
  include:
    # Frontend OSX
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      script:
        - cd app && npm install && npm run build:macos

    # Admin Panel OSX
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      script:
        - cd adminPanel && npm install && npm run build:macos

    # Frontend Linux - Windows
    - os: linux
      services: docker
      language: node_js
      script:
        - |
          docker run $ENVS --rm \
            -v ${PWD}:/project \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine \
            /bin/bash -c "cd app && npm install && npm run build:win-linux"

    # Admin Panel Windows - Linux
    - os: linux
      services: docker
      language: node_js
      script:
        - |
          docker run $ENVS --rm \
            -v ${PWD}:/project \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine \
            /bin/bash -c "cd adminPanel && npm install && npm run build:win-linux"

    # Backend
    - os: linux
      language: go
      go:
        - "1.12"
      script:
        - make .build-go
      env:
        - GO111MODULE=on

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
    - "dev"