matrix:
  include:
  - os: linux
    language: node_js
    node_js: '10'
    script:
    - make .publish-moniteur-linux
  - os: windows
    language: node_js
    node_js: '10'
    before_install:
    - choco install -y make
    script:
    - make .publish-moniteur-win
  - os: linux
    language: go
    go:
    - '1.12'
    script:
    - make .build-go
    env:
    - GO111MODULE=on
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
