#!/bin/bash
echo "$GH_TOKEN" | docker login https://docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
docker-compose push

sentry-cli releases new -p moniteur $TRAVIS_TAG
sentry-cli releases set-commits --auto $TRAVIS_TAG
sentry-cli releases finalize "$TRAVIS_TAG"
